#!/usr/bin/env python

import dnskeys
import sys

def printOtrFingerprints(jid):
    for fingerprint, dnssec_valid in dnskeys.getOtrFingerprints(jid):
        print ( "V: " if dnssec_valid else "I: " ) + fingerprint

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print "Usage: %s <jabberID>" % (sys.argv[0],)
    else:
        printOtrFingerprints(sys.argv[1])

